"""Synthetic long-read alignment dataset generator.

This module produces a small, fully-labelled synthetic dataset whose statistics
mirror the (non-public) benchmark in AGNES (arXiv:2510.16013v3, Table 1) so the
GraphMambaFormer universal aligner can be exercised end-to-end on a CPU. Every
read is generated by a controlled edit process, so **all ground truth is exact
by construction** — CIGAR, reference span, strand, per-base reference
coordinates, minimizer seeds (true / false), pangenome graph path, MAPQ, and
the modality-specific head labels (methylation, splice, barcode/UMI, chimeric).

Target characteristics (AGNES Table 1):
  * Reference: 40-50% GC content, 10-15% repeat content.
  * Reads: 8-10 kb, 15% error rate (5% ins / 5% del / 5% sub), error rate
    doubled inside homopolymer runs.
  * Seeds: 15-25 true seeds per read via minimizer extraction (k=15, w=10),
    plus 20-30% false seeds from spurious k-mer matches.
  * Split: 640 train / 160 validation / 200 test reads.

Because a pure-PyTorch Mamba scan over a 10 kb read is slow on CPU, the default
:class:`SyntheticConfig` uses short reads/genomes (fast full-model forward),
while the ``long`` and ``table1`` presets reproduce the paper-scale numbers for
data-level and encoder-only checks. See :func:`preset`.

Nothing here imports torch — generation is pure Python/stdlib so it stays fast
and portable. The torch-facing ``Dataset`` lives in ``dataset.py``.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import Optional

# --------------------------------------------------------------------------- #
# Alphabet / small helpers
# --------------------------------------------------------------------------- #
BASES = "ACGT"
_BASE2IDX = {"A": 0, "C": 1, "G": 2, "T": 3}
_COMPLEMENT = {"A": "T", "C": "G", "G": "C", "T": "A", "N": "N"}
_MASK64 = (1 << 64) - 1

# Pangenome edge types (Figure 1A: "8 discrete edge types"). The ids double as
# the ``edge_type`` indices consumed by ReferenceGraphEncoder / the future GATv2.
EDGE_TYPES: dict[str, int] = {
    "ref_link": 0,   # linear reference adjacency (backbone)
    "snp": 1,        # SNP bubble alt allele          (match / SNP)
    "insertion": 2,  # insertion bubble               (indel)
    "deletion": 3,   # deletion bypass                 (indel / SV)
    "sv": 4,         # large structural-variant bubble (SV)
    "splice": 5,     # splice junction                 (RNA)
    "cpg": 6,        # CpG correlation link            (methylation)
    "barcode": 7,    # barcode / molecule link         (single-cell / linked)
}


def reverse_complement(seq: str) -> str:
    return "".join(_COMPLEMENT.get(b, "N") for b in reversed(seq))


def gc_content(seq: str) -> float:
    if not seq:
        return 0.0
    gc = sum(1 for b in seq if b in "GC")
    return gc / len(seq)


def _kmer_to_int(kmer: str) -> Optional[int]:
    """2-bit encode an ACGT k-mer; return ``None`` if it contains a non-ACGT base."""
    x = 0
    for c in kmer:
        b = _BASE2IDX.get(c)
        if b is None:
            return None
        x = (x << 2) | b
    return x


def _hash64(x: int) -> int:
    """Invertible 64-bit integer hash (minimap2 ``hash64`` style) for minimizers."""
    x = (~x + (x << 21)) & _MASK64
    x ^= x >> 24
    x = (x + (x << 3) + (x << 8)) & _MASK64
    x ^= x >> 14
    x = (x + (x << 2) + (x << 4)) & _MASK64
    x ^= x >> 28
    x = (x + (x << 31)) & _MASK64
    return x


# --------------------------------------------------------------------------- #
# Data records
# --------------------------------------------------------------------------- #
@dataclass
class Seed:
    """A minimizer anchor between a read and the reference.

    ``read_pos`` / ``ref_pos`` are 0-based start coordinates; ``length`` is the
    minimizer k. ``is_true`` marks an anchor that lies on the read's true
    alignment diagonal (exact match), as opposed to a spurious repeat match.
    ``features`` is a 12-dim vector mirroring the AGNES per-seed node features.
    """

    read_pos: int
    ref_pos: int
    length: int
    strand: int  # +1 forward, -1 reverse
    is_true: bool
    features: list[float] = field(default_factory=list)


@dataclass
class PangenomeGraph:
    """A tiny pangenome subgraph for one reference (segments + variant bubbles)."""

    node_seqs: list[str]
    edge_index: list[tuple[int, int]]  # (src, dst) node indices
    edge_type: list[int]               # EDGE_TYPES id per edge
    backbone_path: list[int]           # node ids forming the linear reference
    node_ref_start: list[int]          # reference start coord for each node (-1 for alt)


@dataclass
class Reference:
    ref_id: int
    seq: str
    gc_content: float
    repeat_content: float
    repeat_mask: list[bool]  # True where the base belongs to an inserted repeat
    graph: PangenomeGraph


@dataclass
class ReadRecord:
    """A simulated read with exact ground truth for every pipeline stage."""

    read_id: str
    ref_id: int
    modality: str

    seq: str
    quals: list[int]              # per-base Phred qualities (aligned to ``seq``)

    # --- alignment ground truth (Figure 1C: alignment head) ---------------- #
    ref_start: int                # inclusive, on the forward reference
    ref_end: int                  # exclusive
    strand: int                   # +1 / -1
    cigar: list[tuple[str, int]]  # ops over the read, using '=', 'X', 'I', 'D'
    ref_positions: list[int]      # per read base: forward-ref coord, or -1 (insertion)
    mapq: int                     # Figure 1C: MAPQ head target (0-60)

    # --- seed chaining ground truth (Figure 1B Layer 1) -------------------- #
    seeds: list[Seed] = field(default_factory=list)

    # --- modality-conditional heads (Figure 1C) --------------------------- #
    methylation: list[tuple[int, int]] = field(default_factory=list)  # (read_pos, 0/1)
    splice_junctions: list[tuple[int, int]] = field(default_factory=list)  # (donor, acceptor) read pos
    barcode: Optional[str] = None
    umi: Optional[str] = None
    is_chimeric: bool = False
    supplementary: Optional[dict] = None  # second alignment for chimeric reads

    edge_case: Optional[str] = None       # tag for injected edge cases

    # -- convenience ------------------------------------------------------- #
    @property
    def cigar_string(self) -> str:
        return "".join(f"{n}{op}" for op, n in self.cigar)

    @property
    def num_true_seeds(self) -> int:
        return sum(1 for s in self.seeds if s.is_true)

    @property
    def num_false_seeds(self) -> int:
        return sum(1 for s in self.seeds if not s.is_true)


@dataclass
class SyntheticDataset:
    references: dict[int, Reference]
    splits: dict[str, list[ReadRecord]]
    config: "SyntheticConfig"

    def all_records(self) -> list[ReadRecord]:
        out: list[ReadRecord] = []
        for recs in self.splits.values():
            out.extend(recs)
        return out


# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
@dataclass
class SyntheticConfig:
    # reproducibility
    seed: int = 0

    # references
    num_references: int = 2
    ref_len: int = 6_000
    gc_min: float = 0.40
    gc_max: float = 0.50
    repeat_min: float = 0.10
    repeat_max: float = 0.15
    repeat_unit_min: int = 40
    repeat_unit_max: int = 120
    homopolymer_frac: float = 0.03  # fraction of ref seeded with homopolymer runs

    # reads. The default ~1.5-2.5 kb is the shortest length that still yields
    # the paper's 15-25 true minimizer seeds under a 15% error rate with
    # (k=15, w=10); the model forward can truncate via ``max_read_len`` to keep
    # the CPU Mamba scan fast. The ``long`` preset uses the true 8-10 kb.
    read_len_min: int = 1_500
    read_len_max: int = 2_500
    p_ins: float = 0.05
    p_del: float = 0.05
    p_sub: float = 0.05
    homopolymer_error_multiplier: float = 2.0
    homopolymer_min_run: int = 3  # run length at which the error rate doubles
    reverse_frac: float = 0.5        # fraction of reads on the reverse strand
    qual_match: tuple[int, int] = (30, 40)
    qual_error: tuple[int, int] = (2, 15)

    # seeds (minimizers)
    kmer: int = 15
    window: int = 10
    true_seed_min: int = 15
    true_seed_max: int = 25
    false_seed_frac_min: float = 0.20
    false_seed_frac_max: float = 0.30

    # split sizes (reads)
    n_train: int = 8
    n_val: int = 2
    n_test: int = 2

    # modalities used for the "main" reads (long-read focus)
    modalities: tuple[str, ...] = ("pacbio_hifi", "ont")
    # add one specialised read per extra modality (rna_seq/bisulfite/etc.)
    include_all_modalities: bool = False
    # append tagged edge-case reads in a dedicated ``edge`` split
    include_edge_cases: bool = True

    def validate(self) -> None:
        if self.kmer < 1 or self.window < 1:
            raise ValueError("kmer and window must be >= 1")
        if self.read_len_max < self.read_len_min:
            raise ValueError("read_len_max < read_len_min")
        if self.ref_len < self.read_len_max + 1:
            raise ValueError("ref_len must exceed read_len_max")


def preset(name: str) -> SyntheticConfig:
    """Return a named configuration.

    * ``"tiny"``   — short reads/genomes; a few samples. Full model forward
      passes are fast on CPU. (default-ish, used for quick correctness tests)
    * ``"long"``   — paper-scale 8-10 kb reads on ~80 kb references, a handful
      of samples. Data-level + encoder checks; the Mamba backbone over 10 kb is
      slow on CPU, so use encoder-only / truncated runs for the model.
    * ``"table1"`` — exact AGNES split (640/160/200) at 8-10 kb. Heavy; intended
      for when a GPU is available.
    """
    name = name.lower()
    if name == "tiny":
        return SyntheticConfig()
    if name == "long":
        return SyntheticConfig(
            num_references=2,
            ref_len=80_000,
            read_len_min=8_000,
            read_len_max=10_000,
            n_train=6,
            n_val=2,
            n_test=2,
        )
    if name == "table1":
        return SyntheticConfig(
            num_references=4,
            ref_len=200_000,
            read_len_min=8_000,
            read_len_max=10_000,
            n_train=640,
            n_val=160,
            n_test=200,
            include_all_modalities=True,
        )
    raise ValueError(f"Unknown preset {name!r}. Choose from tiny|long|table1.")


# --------------------------------------------------------------------------- #
# Reference generation
# --------------------------------------------------------------------------- #
def _random_seq(rng: random.Random, n: int, gc: float) -> str:
    """Random ACGT sequence whose expected GC content equals ``gc``."""
    out = []
    for _ in range(n):
        if rng.random() < gc:
            out.append(rng.choice("GC"))
        else:
            out.append(rng.choice("AT"))
    return "".join(out)


def _generate_reference(rng: random.Random, cfg: SyntheticConfig, ref_id: int) -> Reference:
    gc_target = rng.uniform(cfg.gc_min, cfg.gc_max)
    repeat_target = rng.uniform(cfg.repeat_min, cfg.repeat_max)
    n = cfg.ref_len

    seq = list(_random_seq(rng, n, gc_target))
    repeat_mask = [False] * n

    # Insert a small family of repeat elements (copies of shared units) until we
    # reach the target repeat fraction. Repeated k-mers create genuine spurious
    # (false) seed matches downstream.
    target_repeat_bases = int(repeat_target * n)
    repeat_bases = 0
    # a couple of distinct repeat "families"
    n_families = max(1, rng.randint(1, 3))
    families = [
        _random_seq(rng, rng.randint(cfg.repeat_unit_min, cfg.repeat_unit_max), gc_target)
        for _ in range(n_families)
    ]
    guard = 0
    while repeat_bases < target_repeat_bases and guard < 10_000:
        guard += 1
        unit = rng.choice(families)
        # occasionally lay down a tandem array (several copies back-to-back)
        copies = rng.choice([1, 1, 2, 3])
        block = unit * copies
        L = len(block)
        if L >= n:
            continue
        pos = rng.randint(0, n - L)
        # avoid clobbering an existing repeat too much
        if any(repeat_mask[pos : pos + L]):
            continue
        seq[pos : pos + L] = list(block)
        for j in range(pos, pos + L):
            repeat_mask[j] = True
        repeat_bases += L

    # Sprinkle homopolymer runs (for the homopolymer error-doubling test).
    n_homop = int(cfg.homopolymer_frac * n / 8)
    for _ in range(n_homop):
        run = rng.randint(5, 10)
        pos = rng.randint(0, n - run)
        base = rng.choice(BASES)
        seq[pos : pos + run] = [base] * run

    seq_str = "".join(seq)
    graph = _build_graph(rng, cfg, seq_str, repeat_mask)
    return Reference(
        ref_id=ref_id,
        seq=seq_str,
        gc_content=gc_content(seq_str),
        repeat_content=sum(repeat_mask) / n,
        repeat_mask=repeat_mask,
        graph=graph,
    )


def _build_graph(
    rng: random.Random, cfg: SyntheticConfig, ref_seq: str, repeat_mask: list[bool]
) -> PangenomeGraph:
    """Build a linear-backbone pangenome graph with a few variant bubbles.

    Nodes are contiguous reference segments; consecutive segments are joined by
    ``ref_link`` edges. A handful of alt nodes (SNP / insertion / deletion / SV)
    add bubbles with the corresponding edge types.
    """
    n = len(ref_seq)
    # segment the backbone into ~200 bp nodes (bounded for tiny genomes)
    seg_len = max(50, min(200, n // 6 or n))
    bounds = list(range(0, n, seg_len))
    if bounds[-1] != n:
        bounds.append(n)

    node_seqs: list[str] = []
    node_ref_start: list[int] = []
    backbone: list[int] = []
    for i in range(len(bounds) - 1):
        s, e = bounds[i], bounds[i + 1]
        node_seqs.append(ref_seq[s:e])
        node_ref_start.append(s)
        backbone.append(i)

    edge_index: list[tuple[int, int]] = []
    edge_type: list[int] = []
    for a, b in zip(backbone[:-1], backbone[1:]):
        edge_index.append((a, b))
        edge_type.append(EDGE_TYPES["ref_link"])

    # add up to a few bubbles hanging off interior backbone nodes
    bubble_specs = [
        ("snp", EDGE_TYPES["snp"]),
        ("insertion", EDGE_TYPES["insertion"]),
        ("deletion", EDGE_TYPES["deletion"]),
        ("sv", EDGE_TYPES["sv"]),
    ]
    n_bubbles = min(len(bubble_specs), max(0, len(backbone) - 2))
    for i in range(n_bubbles):
        kind, etype = bubble_specs[i]
        anchor = backbone[1 + i]  # interior node
        nxt = anchor + 1 if (anchor + 1) in backbone else anchor
        if kind == "deletion":
            # deletion bypass: skip the next backbone node
            skip_to = min(anchor + 2, backbone[-1])
            edge_index.append((anchor, skip_to))
            edge_type.append(etype)
            continue
        # SNP / insertion / SV: add an alt node and wire in+out
        base = node_seqs[anchor][: max(1, len(node_seqs[anchor]) // 2)]
        if kind == "snp":
            alt = _mutate_one(rng, base)
        elif kind == "insertion":
            alt = base + _random_seq(rng, rng.randint(3, 15), 0.5)
        else:  # sv
            alt = _random_seq(rng, rng.randint(30, 80), 0.5)
        alt_id = len(node_seqs)
        node_seqs.append(alt)
        node_ref_start.append(-1)
        edge_index.append((anchor, alt_id))
        edge_type.append(etype)
        edge_index.append((alt_id, nxt))
        edge_type.append(etype)

    return PangenomeGraph(
        node_seqs=node_seqs,
        edge_index=edge_index,
        edge_type=edge_type,
        backbone_path=backbone,
        node_ref_start=node_ref_start,
    )


def _mutate_one(rng: random.Random, seq: str) -> str:
    if not seq:
        return seq
    i = rng.randint(0, len(seq) - 1)
    alt = rng.choice([b for b in BASES if b != seq[i]])
    return seq[:i] + alt + seq[i + 1 :]


# --------------------------------------------------------------------------- #
# Read simulation (controlled edit process -> exact CIGAR)
# --------------------------------------------------------------------------- #
def _phred(rng: random.Random, lo_hi: tuple[int, int]) -> int:
    return rng.randint(lo_hi[0], lo_hi[1])


def _simulate_read(
    rng: random.Random,
    cfg: SyntheticConfig,
    ref: Reference,
    read_id: str,
    modality: str,
    *,
    ref_start: Optional[int] = None,
    read_len: Optional[int] = None,
    strand: Optional[int] = None,
    force_region_repeat: bool = False,
) -> ReadRecord:
    """Simulate one read by editing an oriented reference substring.

    Returns a fully-labelled :class:`ReadRecord`. The template is the reference
    substring in *read orientation* (reverse-complemented for ``strand == -1``),
    and every read base carries its forward-reference coordinate, giving an exact
    CIGAR and exact minimizer true/false labels.
    """
    n = len(ref.seq)
    if read_len is None:
        read_len = rng.randint(cfg.read_len_min, cfg.read_len_max)
    read_len = max(1, min(read_len, n - 1))

    if ref_start is None:
        if force_region_repeat and any(ref.repeat_mask):
            # anchor the read inside a repeat-heavy region
            idxs = [i for i, m in enumerate(ref.repeat_mask[: n - read_len]) if m]
            ref_start = rng.choice(idxs) if idxs else rng.randint(0, n - read_len)
        else:
            ref_start = rng.randint(0, n - read_len)
    ref_end = min(ref_start + read_len, n)

    if strand is None:
        strand = -1 if rng.random() < cfg.reverse_frac else 1

    template = ref.seq[ref_start:ref_end]
    if strand == -1:
        template = reverse_complement(template)

    def tmpl_to_ref(i: int) -> int:
        # forward-reference coordinate of template position i
        return ref_start + i if strand == 1 else ref_end - 1 - i

    read_chars: list[str] = []
    quals: list[int] = []
    ref_positions: list[int] = []
    ops: list[str] = []  # per-emitted-symbol op, using '=', 'X', 'I', 'D'

    prev_base = None
    run_len = 0
    for i, base in enumerate(template):
        run_len = run_len + 1 if base == prev_base else 1
        # a homopolymer run doubles the error rate only once it is long enough
        homop = run_len >= cfg.homopolymer_min_run
        mult = cfg.homopolymer_error_multiplier if homop else 1.0
        p_del = min(0.95, cfg.p_del * mult)
        p_ins = min(0.95, cfg.p_ins * mult)
        p_sub = min(0.95, cfg.p_sub * mult)
        prev_base = base

        # insertion(s) before consuming this template base
        while rng.random() < p_ins:
            read_chars.append(rng.choice(BASES))
            quals.append(_phred(rng, cfg.qual_error))
            ref_positions.append(-1)
            ops.append("I")

        r = rng.random()
        if r < p_del:
            ops.append("D")  # consumes reference, not read
            continue
        if r < p_del + p_sub:
            alt = rng.choice([b for b in BASES if b != base])
            read_chars.append(alt)
            quals.append(_phred(rng, cfg.qual_error))
            ref_positions.append(tmpl_to_ref(i))
            ops.append("X")
        else:
            read_chars.append(base)
            quals.append(_phred(rng, cfg.qual_match))
            ref_positions.append(tmpl_to_ref(i))
            ops.append("=")

    # trailing insertions
    while rng.random() < cfg.p_ins:
        read_chars.append(rng.choice(BASES))
        quals.append(_phred(rng, cfg.qual_error))
        ref_positions.append(-1)
        ops.append("I")

    seq = "".join(read_chars)
    cigar = _rle_cigar(ops)
    mapq = _estimate_mapq(cfg, ref, ref_start, ref_end)

    rec = ReadRecord(
        read_id=read_id,
        ref_id=ref.ref_id,
        modality=modality,
        seq=seq,
        quals=quals,
        ref_start=ref_start,
        ref_end=ref_end,
        strand=strand,
        cigar=cigar,
        ref_positions=ref_positions,
        mapq=mapq,
    )
    rec.seeds = _extract_seeds(rng, cfg, ref, rec)
    return rec


def _rle_cigar(ops: list[str]) -> list[tuple[str, int]]:
    cigar: list[tuple[str, int]] = []
    for op in ops:
        if cigar and cigar[-1][0] == op:
            cigar[-1] = (op, cigar[-1][1] + 1)
        else:
            cigar.append((op, 1))
    return cigar


def _estimate_mapq(cfg: SyntheticConfig, ref: Reference, start: int, end: int) -> int:
    span = ref.repeat_mask[start:end]
    repeat_frac = (sum(span) / len(span)) if span else 0.0
    mapq = int(round(60 * (1.0 - repeat_frac)))
    return max(0, min(60, mapq))


# --------------------------------------------------------------------------- #
# Minimizer seeds (true + false)
# --------------------------------------------------------------------------- #
def minimizers(seq: str, k: int, w: int) -> list[tuple[int, int, int]]:
    """Standard (w, k) minimizer sketch.

    Returns a list of ``(pos, kmer_int, hash)`` for the selected minimizers,
    de-duplicated on consecutive identical positions.
    """
    m = len(seq) - k + 1
    if m <= 0:
        return []
    khs: list[tuple[int, Optional[int], Optional[int]]] = []
    for i in range(m):
        ki = _kmer_to_int(seq[i : i + k])
        khs.append((i, ki, _hash64(ki) if ki is not None else None))

    out: list[tuple[int, int, int]] = []
    last_pos = -1
    win = max(1, w)
    for start in range(0, max(1, m - win + 1)):
        window = khs[start : start + win]
        valid = [t for t in window if t[2] is not None]
        if not valid:
            continue
        pos, ki, h = min(valid, key=lambda t: (t[2], t[0]))
        if pos != last_pos:
            out.append((pos, ki, h))
            last_pos = pos
    return out


def _build_ref_kmer_index(seq: str, k: int) -> dict[int, list[int]]:
    idx: dict[int, list[int]] = {}
    for i in range(len(seq) - k + 1):
        ki = _kmer_to_int(seq[i : i + k])
        if ki is None:
            continue
        idx.setdefault(ki, []).append(i)
    return idx


# cache of (ref_id, k) -> (fwd_index, rc_index) to avoid recompute across reads
_REF_INDEX_CACHE: dict[tuple[int, int, int], tuple[dict, dict]] = {}


def _get_ref_indices(ref: Reference, k: int) -> tuple[dict, dict]:
    key = (id(ref), ref.ref_id, k)
    cached = _REF_INDEX_CACHE.get(key)
    if cached is None:
        fwd = _build_ref_kmer_index(ref.seq, k)
        rc = _build_ref_kmer_index(reverse_complement(ref.seq), k)
        cached = (fwd, rc)
        _REF_INDEX_CACHE[key] = cached
    return cached


def _extract_seeds(
    rng: random.Random, cfg: SyntheticConfig, ref: Reference, rec: ReadRecord
) -> list[Seed]:
    """Minimizer extraction + true/false labelling using the exact alignment.

    True seeds  = read minimizers whose k-mer maps, base-for-base, to a
                  contiguous exact match on the read's true diagonal.
    False seeds = read minimizer k-mers that also occur in the reference at an
                  off-diagonal position (spurious repeat matches).
    """
    k, w = cfg.kmer, cfg.window
    mins = minimizers(rec.seq, k, w)
    if not mins:
        return []

    # read base -> forward-ref coord (or -1 for insertion)
    rpos = rec.ref_positions
    L = len(rec.seq)
    fwd_idx, rc_idx = _get_ref_indices(ref, k)
    n = len(ref.seq)

    true_candidates: list[Seed] = []
    false_pool: list[Seed] = []

    for pos, ki, h in mins:
        if pos + k > L:
            continue
        span = rpos[pos : pos + k]
        # a true anchor requires all k read bases to be aligned matches ('=')
        # forming a contiguous run in reference coordinates (per strand).
        is_true = all(p >= 0 for p in span)
        if is_true:
            step = 1 if rec.strand == 1 else -1
            for a, b in zip(span[:-1], span[1:]):
                if b - a != step:
                    is_true = False
                    break
            # and the k read bases must equal the reference (no substitution)
            if is_true:
                ref_lo = min(span)
                sub = ref.seq[ref_lo : ref_lo + k]
                expect = rec.seq[pos : pos + k]
                if rec.strand == -1:
                    expect = reverse_complement(expect)
                if sub != expect:
                    is_true = False
        if is_true:
            ref_lo = min(span)
            true_candidates.append(
                Seed(read_pos=pos, ref_pos=ref_lo, length=k, strand=rec.strand, is_true=True)
            )
            continue

        # otherwise look for a genuine spurious occurrence in the reference
        index = fwd_idx if rec.strand == 1 else rc_idx
        if ki in index:
            # pick an occurrence off the true diagonal
            diag_expect = min((p for p in span if p >= 0), default=None)
            for occ in index[ki]:
                ref_coord = occ if rec.strand == 1 else (n - k - occ)
                if diag_expect is None or abs(ref_coord - diag_expect) > k:
                    false_pool.append(
                        Seed(read_pos=pos, ref_pos=ref_coord, length=k, strand=rec.strand, is_true=False)
                    )
                    break

    # subsample true seeds to the target range [true_seed_min, true_seed_max]
    rng.shuffle(true_candidates)
    n_true_target = rng.randint(cfg.true_seed_min, cfg.true_seed_max)
    true_seeds = true_candidates[:n_true_target]
    n_true = len(true_seeds)

    # choose a false fraction and (if needed) synthesise off-diagonal spurious
    # seeds so the ratio lands in [false_frac_min, false_frac_max].
    frac = rng.uniform(cfg.false_seed_frac_min, cfg.false_seed_frac_max)
    n_false_target = int(round(frac / (1 - frac) * n_true)) if n_true else 0
    rng.shuffle(false_pool)
    false_seeds = false_pool[:n_false_target]
    while len(false_seeds) < n_false_target and n_true:
        # synthetic spurious seed at a random off-diagonal reference position
        pos, ki, h = rng.choice(mins)
        ref_coord = rng.randint(0, max(0, n - k))
        false_seeds.append(
            Seed(read_pos=pos, ref_pos=ref_coord, length=k, strand=rec.strand, is_true=False)
        )

    seeds = true_seeds + false_seeds
    seeds.sort(key=lambda s: s.read_pos)
    _attach_seed_features(cfg, ref, rec, seeds)
    return seeds


def _attach_seed_features(
    cfg: SyntheticConfig, ref: Reference, rec: ReadRecord, seeds: list[Seed]
) -> None:
    """Populate the 12-dim per-seed feature vector (AGNES-style)."""
    k = cfg.kmer
    read_len = max(1, len(rec.seq))
    ref_len = max(1, len(ref.seq))
    fwd_idx, _ = _get_ref_indices(ref, k)
    read_pos_sorted = [s.read_pos for s in seeds]

    for i, s in enumerate(seeds):
        # local GC + repeat overlap around the seed's reference span
        r0 = max(0, min(ref_len - 1, s.ref_pos))
        r1 = min(ref_len, r0 + k)
        local = ref.seq[r0:r1]
        repeat_overlap = (
            sum(ref.repeat_mask[r0:r1]) / max(1, (r1 - r0))
        )
        # k-mer uniqueness in the reference (1 / occurrence count)
        ki = _kmer_to_int(rec.seq[s.read_pos : s.read_pos + k])
        occ = len(fwd_idx.get(ki, [])) if ki is not None else 0
        uniqueness = 1.0 / occ if occ else 0.0
        # minimizer hash rank proxy in [0, 1] (label-free)
        hash_rank = (_hash64(ki) / _MASK64) if ki is not None else 0.0
        # mean base quality over the seed span in the read
        q = rec.quals[s.read_pos : s.read_pos + k]
        mean_q = (sum(q) / len(q)) if q else 0.0
        # neighbour gaps
        gap_prev = (s.read_pos - read_pos_sorted[i - 1]) if i > 0 else 0
        gap_next = (read_pos_sorted[i + 1] - s.read_pos) if i + 1 < len(seeds) else 0

        s.features = [
            s.read_pos / read_len,                 # 0  read position
            s.ref_pos / ref_len,                   # 1  reference position
            (s.ref_pos - s.read_pos) / ref_len,    # 2  diagonal offset
            float(s.strand),                       # 3  strand
            k / read_len,                          # 4  seed length (fraction)
            gc_content(local),                     # 5  local GC content
            repeat_overlap,                        # 6  repeat overlap
            uniqueness,                            # 7  k-mer uniqueness
            mean_q / 60.0,                         # 8  mean base quality
            hash_rank,                             # 9  minimizer hash rank (label-free)
            gap_prev / read_len,                   # 10 gap to previous seed
            gap_next / read_len,                   # 11 gap to next seed
        ]


# --------------------------------------------------------------------------- #
# Modality-specific decoration
# --------------------------------------------------------------------------- #
def _flip_cigar_op_at_read_pos(
    cigar: list[tuple[str, int]], read_pos: int, new_op: str = "X"
) -> list[tuple[str, int]]:
    """Return a CIGAR with the query-consuming op at ``read_pos`` set to ``new_op``.

    Only affects query-consuming ops (``=``, ``X``, ``I``, ``S``); no-op if the
    position lands on a non-``=`` op (so conversions on insertions are ignored).
    """
    ops: list[str] = []
    for op, n in cigar:
        ops.extend([op] * n)
    q = -1  # index into query-consuming symbols
    for idx, op in enumerate(ops):
        if op in ("=", "X", "I", "S"):
            q += 1
            if q == read_pos:
                if op == "=":
                    ops[idx] = new_op
                break
    return _rle_cigar(ops)


def _op_at_read_pos(cigar: list[tuple[str, int]], read_pos: int) -> Optional[str]:
    """Return the query-consuming CIGAR op covering ``read_pos`` (or ``None``)."""
    q = 0  # first query index of the current op
    for op, n in cigar:
        if op in ("=", "X", "I", "S"):
            if q <= read_pos < q + n:
                return op
            q += n
    return None


def _decorate_modality(rng: random.Random, cfg: SyntheticConfig, rec: ReadRecord) -> None:
    """Add modality-conditional head labels (Figure 1C)."""
    m = rec.modality
    if m == "bisulfite":
        # methylation state at CpG sites; unmethylated C -> T "conversion". A
        # conversion is a real sequence change vs. the reference, so the truth
        # CIGAR op at that position becomes a mismatch ('X').
        chars = list(rec.seq)
        for i in range(len(chars) - 1):
            # only genomic (reference-matched) cytosines are bisulfite substrates
            if chars[i] == "C" and chars[i + 1] == "G" and _op_at_read_pos(rec.cigar, i) == "=":
                methylated = rng.random() < 0.5
                rec.methylation.append((i, int(methylated)))
                if not methylated:
                    chars[i] = "T"  # bisulfite conversion -> now a mismatch
                    rec.cigar = _flip_cigar_op_at_read_pos(rec.cigar, i, "X")
        rec.seq = "".join(chars)
    elif m == "rna_seq":
        # a splice junction = a large gap; label its read-position boundary
        if len(rec.seq) > 20:
            donor = len(rec.seq) // 2
            rec.splice_junctions.append((donor, donor + 1))
    elif m in ("single_cell", "linked_reads"):
        rec.barcode = "".join(rng.choice(BASES) for _ in range(16))
        rec.umi = "".join(rng.choice(BASES) for _ in range(12))
        prefix = rec.barcode + rec.umi
        rec.seq = prefix + rec.seq
        rec.quals = [cfg.qual_match[1]] * len(prefix) + rec.quals
        rec.ref_positions = [-1] * len(prefix) + rec.ref_positions
        rec.cigar = [("S", len(prefix))] + rec.cigar  # soft-clip the barcode/UMI


# --------------------------------------------------------------------------- #
# Edge cases
# --------------------------------------------------------------------------- #
def _make_edge_cases(rng: random.Random, cfg: SyntheticConfig, refs: list[Reference]) -> list[ReadRecord]:
    ref = refs[0]
    cases: list[ReadRecord] = []

    def tag(rec: ReadRecord, name: str) -> ReadRecord:
        rec.edge_case = name
        return rec

    # 1. empty read
    cases.append(
        tag(
            ReadRecord(
                read_id="edge_empty", ref_id=ref.ref_id, modality="ont", seq="",
                quals=[], ref_start=0, ref_end=0, strand=1, cigar=[], ref_positions=[], mapq=0,
            ),
            "empty_read",
        )
    )

    # 2. very short read (< k)
    short = _simulate_read(rng, cfg, ref, "edge_short", "ont", read_len=cfg.kmer - 3, strand=1)
    cases.append(tag(short, "shorter_than_k"))

    # 3. all-N read (UNK tokens throughout)
    ncase = ReadRecord(
        read_id="edge_all_n", ref_id=ref.ref_id, modality="ont", seq="N" * 60,
        quals=[10] * 60, ref_start=0, ref_end=0, strand=1, cigar=[("I", 60)],
        ref_positions=[-1] * 60, mapq=0,
    )
    cases.append(tag(ncase, "all_n_read"))

    # 4. homopolymer-only read: a low-complexity read that does not map
    #    uniquely (unmapped), exercising homopolymer tokenization/encoding.
    base = rng.choice(BASES)
    hp = base * 80
    hp_rec = ReadRecord(
        read_id="edge_homopolymer", ref_id=ref.ref_id, modality="ont", seq=hp,
        quals=[15] * len(hp), ref_start=0, ref_end=0, strand=1,
        cigar=[("I", len(hp))], ref_positions=[-1] * len(hp), mapq=0,
    )
    cases.append(tag(hp_rec, "homopolymer_only"))

    # 5. fully-repeat read (many false seeds, low MAPQ)
    rep = _simulate_read(rng, cfg, ref, "edge_repeat", "ont", force_region_repeat=True, strand=1)
    cases.append(tag(rep, "repeat_region"))

    # 6. reverse-strand read
    revr = _simulate_read(rng, cfg, ref, "edge_reverse", "pacbio_hifi", strand=-1)
    cases.append(tag(revr, "reverse_strand"))

    # 7. chimeric read (two distant reference regions concatenated)
    a = _simulate_read(rng, cfg, ref, "edge_chimeric_a", "ont",
                       ref_start=0, read_len=cfg.read_len_min // 2, strand=1)
    b = _simulate_read(rng, cfg, ref, "edge_chimeric_b", "ont",
                       ref_start=len(ref.seq) - cfg.read_len_min, read_len=cfg.read_len_min // 2, strand=1)
    chim = ReadRecord(
        read_id="edge_chimeric", ref_id=ref.ref_id, modality="ont",
        seq=a.seq + b.seq, quals=a.quals + b.quals,
        ref_start=a.ref_start, ref_end=a.ref_end, strand=1,
        cigar=a.cigar + [("S", len(b.seq))],
        ref_positions=a.ref_positions + [-1] * len(b.seq),
        mapq=min(a.mapq, b.mapq), is_chimeric=True,
        # supplementary aligns the b-part; soft-clip the a-part so its CIGAR
        # spans the full read (reciprocal of the primary's trailing soft-clip).
        supplementary={"ref_start": b.ref_start, "ref_end": b.ref_end,
                       "strand": b.strand, "cigar": [("S", len(a.seq))] + b.cigar},
    )
    chim.seeds = _extract_seeds(rng, cfg, ref, chim)
    cases.append(tag(chim, "chimeric"))

    return cases


# --------------------------------------------------------------------------- #
# Top-level generation
# --------------------------------------------------------------------------- #
def generate_dataset(cfg: Optional[SyntheticConfig] = None) -> SyntheticDataset:
    """Generate a fully-labelled synthetic dataset from ``cfg`` (default: tiny)."""
    cfg = cfg or SyntheticConfig()
    cfg.validate()
    rng = random.Random(cfg.seed)
    _REF_INDEX_CACHE.clear()

    references = {
        rid: _generate_reference(rng, cfg, rid) for rid in range(cfg.num_references)
    }
    ref_list = list(references.values())

    def make_reads(n: int, split: str) -> list[ReadRecord]:
        recs: list[ReadRecord] = []
        for i in range(n):
            ref = ref_list[i % len(ref_list)]
            modality = cfg.modalities[i % len(cfg.modalities)]
            rec = _simulate_read(rng, cfg, ref, f"{split}_{i}", modality)
            _decorate_modality(rng, cfg, rec)
            recs.append(rec)
        return recs

    splits: dict[str, list[ReadRecord]] = {
        "train": make_reads(cfg.n_train, "train"),
        "val": make_reads(cfg.n_val, "val"),
        "test": make_reads(cfg.n_test, "test"),
    }

    if cfg.include_all_modalities:
        extra = [m for m in ("rna_seq", "bisulfite", "single_cell", "linked_reads")]
        specials: list[ReadRecord] = []
        for j, m in enumerate(extra):
            ref = ref_list[j % len(ref_list)]
            rec = _simulate_read(rng, cfg, ref, f"modality_{m}", m)
            _decorate_modality(rng, cfg, rec)
            specials.append(rec)
        splits["modality"] = specials

    if cfg.include_edge_cases:
        splits["edge"] = _make_edge_cases(rng, cfg, ref_list)

    return SyntheticDataset(references=references, splits=splits, config=cfg)


# --------------------------------------------------------------------------- #
# Reconstruction / verification helpers (used by scripts/verify_stages.py)
# --------------------------------------------------------------------------- #
def cigar_consumed(cigar: list[tuple[str, int]]) -> tuple[int, int]:
    """Return (query_len, ref_len) consumed by a CIGAR (ops '=','X','I','D','S')."""
    q = r = 0
    for op, n in cigar:
        if op in ("=", "X"):
            q += n
            r += n
        elif op == "I" or op == "S":
            q += n
        elif op == "D":
            r += n
    return q, r


def verify_read_alignment(rec: ReadRecord, ref: Reference) -> list[str]:
    """Return a list of human-readable problems ('' means fully consistent)."""
    problems: list[str] = []
    q, r = cigar_consumed(rec.cigar)
    if q != len(rec.seq):
        problems.append(f"CIGAR query len {q} != read len {len(rec.seq)}")
    if not rec.is_chimeric and rec.edge_case not in ("all_n_read",):
        expected_ref = rec.ref_end - rec.ref_start
        if r != expected_ref and rec.edge_case is None:
            problems.append(f"CIGAR ref len {r} != span {expected_ref}")
    if len(rec.ref_positions) != len(rec.seq):
        problems.append("ref_positions length != read length")
    return problems
